### ISSUE TITLE
Streamdeck Plugin does not save values

### ISSUE THREAD

**Issue by LukasKurthRocks** [nicollasricas/streamdeck-unity#1]
Hey,

I like this plugin. Unfortunately I can't seem to get the paths to work.
All buttons without properties, like Reset and Pause work like expected.

Only the Menu and Rotate functions do not work as **_the values do not get saved_**.

Version of StreamDeck: 4.6.1.12887
StreamDeck Firmware: 1.00.007
StreamDeck-Unity Plug-In Version: 1.0.0

Could not find a log file for this plugin, but you might have an idea, what could be the cause to this.

Have a nice day :)

**Comment by Justin99b** [comment]
Any Updates on this issue?
Having the same issue.
If not im propably going to to fix it and send him a pull request

**Comment by AlexanderMelde** [comment]
+1, got the same problem

**Comment by nicollasricas** [comment]
Hi,

What menus are you trying to execute? Could you send me an example?

About the rotate values not been saved were you on play mode?

Sorry for the late reply, for some reason I did not receive a notification about this issue and also I've moved to Unreal Engine, but I will fix it as we go further in the investigation.

**Comment by nicollasricas** [comment]
Were the values changed on the editor UI after you pressed?

**Comment by nicollasricas** [comment]
> Could not find a log file for this plugin, but you might have an idea, what could be the cause to this.

%appdata%\Elgato\StreamDeck\Plugins\com.nicollasr.streamdeckunity.sdPlugin\pluginlog.log

**Comment by MarcTowler** [comment]
I also am having this issue, I was trying to execute the Build and Run function under File as an example with no luck, no errors in the log

**Comment by nicollasricas** [comment]
Fixed, download manually [here ](https://github.com/nicollasricas/streamdeck-unity/releases/latest)or wait for Elgato to update on the Stream Deck store.
