### ISSUE TITLE
How to remove the Package?

### ISSUE THREAD

**Issue by Sonny-Crockett** [nicollasricas/streamdeck-unity#2]
I don't see it in the Packages Manager however I see it connecting in the console. Thanks!

**Comment by nicollasricas** [comment]
You have to install the plugin on Stream Deck and import a package into your project as described [here](https://github.com/nicollasricas/streamdeck-unity#getting-started).

**How to uninstall? Delete the package folder from your project and uninstall the plugin on Stream Deck.**

Sorry for the late reply, for some reason I did not receive a notification about this issue.
