### ISSUE TITLE
Console spam is really annoying

### ISSUE THREAD

**Issue by lordubbe** [nicollasricas/streamdeck-unity#3]
While it can be useful to know if anything goes wrong and so on, I really miss a simple verbosity toggle. Whenever I work on my laptop (which does not have a streamdeck connected) the console is flooded with annoying messages.

**Comment by lordubbe** [comment]
Also thanks for this package, it is super helpful :)

**Comment by Sonny-Crockett** [comment]
You can disable that in the Module settings.

**Comment by nicollasricas** [comment]
Hi,

What spamming messages are you referring to? The connected and disconnected messages?

I could provide an option to disable those messages, but whenever Unity recompiles scripts it closes the connection and reopens, that is something I can't change is the way the engine works... Those messages are only logged so you as a user know if you are or not connected to the stream deck. If not them pressing actions will do nothing.

I will release a new update in a few days, finishing things up right now.

**Comment by lordubbe** [comment]
![image](https://user-images.githubusercontent.com/6771203/112728230-910cda80-8f26-11eb-89c1-3f76f4bf9c95.png)
Here's what I'm talking about :) So many messages simply when entering play mode, and it just keeps trying to reconnect :) Just a simple preference toggle to configure verbosity would be excellent! 
And yeah I definitely think it is the right approach to have the messages enabled by default, but in situations like mine where I work on two different setups where only one has a streamdeck connected it would be nice if I could just set an EditorPref bool to mute the messages since I know it's never gonna connect to a streamdeck!

**Comment by nicollasricas** [comment]
I will add an option (editor pref) to disable the Stream Deck integration.

Entering play mode doesn't affect the connection, the problem in your case is that since one setup doesn't have the Stream Deck Software and plugin installed there's no server to connect.

Thank you.

**Comment by lordubbe** [comment]
Great, Thanks :) and again thanks for the integration at all

**Comment by nicollasricas** [comment]
![image](https://user-images.githubusercontent.com/7860985/113514421-76e18680-953c-11eb-85b0-2aa04ec17b4c.png)

Done! Will be released in the next few days.

**Comment by lordubbe** [comment]
Awesome! My console will be happy ;) 
Great work

**Comment by nicollasricas** [comment]
The new [update](https://github.com/nicollasricas/unity-streamdeck/releases/tag/v1.1.0) was released, there are some new features but it won't work until I update the stream deck plugin.

Remove the older version before updating... the folder structure was changed.
