### ISSUE TITLE
Only print 'Stream Deck - Connected' if Verbose is true

### ISSUE THREAD

**Issue by lordubbe** [nicollasricas/streamdeck-unity#5]
**Is your feature request related to a problem? Please describe.**
While the new **Verbose** option cuts a lot down on the console spam, there is still one annoying message remaining: the 'Stream Deck - Connected' message

**Describe the solution you'd like**
It would be awesome if this message also was muted if the Verbose setting is off. As a user I really don't want to have unnecessary messages in my console (including when Stream Deck connects - which happens eg. after each recompilation). 

**Additional context**
Thanks to the new settings, if the stream deck integration appears to not work, I can go to the settings and enable the Verbose and Debug settings to get a clearer picture of why. It is annoying to constantly be reminded that the integration successfully connects all the time.

**Comment by nicollasricas** [comment]
Done!

https://github.com/nicollasricas/unity-streamdeck/releases/tag/v1.1.1
